---
- hosts: lab
  become: true
  become_method: sudo
  remote_user: vagrant
  tasks:
    - name: Configure Kernel Parameter to Use Reverse Path Filtering by Default
      tags:
        - CCE-26915-9
      sysctl:
        name: net.ipv4.conf.default.rp_filter
        value: 1
        state: present
