Vagrant.configure('2') do |config|
  config.vm.box = 'bento/ubuntu-18.04'

  config.vm.hostname = 'totoro'

  config.vm.network 'private_network', ip: '192.168.33.10'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus   = 2
    vb.memory = '1024'
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.inventory_path = '/etc/ansible/hosts'
    ansible.playbook       = 'example_playbook.yml'
    ansible.limit          = 'lab'
  end
end
